import { useEffect } from "react";
import Router, { useRouter } from "next/router";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useGetPageTitle } from "../hooks/useGetPageTitle";

const ForgotPassword = () => {
  const { status } = useSession();
  const router = useRouter();
  const { title } = useGetPageTitle(router.pathname);

  useEffect(() => {
    if (status === "authenticated") Router.replace("/");
  }, [status]);
  if (status === "loading") return <div>Loading...</div>;

  if (status === "authenticated") return null;
  return (
    <>
      <Head>
        <title>Expense Tracker | {title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>
      <div>HELLO FORGOT PASSWORD</div>
    </>
  );
};

export default ForgotPassword;
