import { type NextPage } from "next";
import { useSession } from "next-auth/react";
import { useEffect } from "react";
import Router, { useRouter } from "next/router";
import Head from "next/head";
import { useGetPageTitle } from "../hooks/useGetPageTitle";
import Loader from "../components/shared/Loader";
import Register from "../components/Register/Register";

const SignUp: NextPage = () => {
  const { status } = useSession();
  const router = useRouter();
  const { title } = useGetPageTitle(router.pathname);

  useEffect(() => {
    if (status === "authenticated") Router.replace("/");
  }, [status]);

  if (status === "loading")
    return (
      <div className="flex h-screen w-full justify-center bg-main">
        <Loader />
      </div>
    );
  if (status === "authenticated") return null;

  return (
    <>
      <Head>
        <title>Expense Tracker | {title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>
      <div className="flex h-screen items-center justify-center bg-main">
        <div className="flex w-[450px] flex-col items-center justify-center rounded-xl bg-secondary py-10">
          <Register />
        </div>
      </div>
    </>
  );
};

export default SignUp;
