import { type NextPage } from "next";
import { signIn, useSession } from "next-auth/react";
import { useEffect } from "react";
import Button from "../components/shared/buttons/Button";
import { BsDiscord } from "react-icons/bs";
import { AiFillGoogleCircle } from "react-icons/ai";
import Router, { useRouter } from "next/router";
import Head from "next/head";
import { useGetPageTitle } from "../hooks/useGetPageTitle";
import Loader from "../components/shared/Loader";

const SignIn: NextPage = () => {
  const { status } = useSession();
  const router = useRouter();
  const { title } = useGetPageTitle(router.pathname);

  // const [userInfo, setUserInfo] = useState({ email: "", password: "" });

  useEffect(() => {
    if (status === "authenticated") Router.replace("/");
  }, [status]);

  if (status === "loading")
    return (
      <div className="flex h-screen w-full justify-center bg-main">
        <Loader />
      </div>
    );
  if (status === "authenticated") return null;

  return (
    <>
      <Head>
        <title>Expense Tracker | {title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>
      <div className="flex h-screen items-center justify-center bg-main">
        <div className="flex w-[450px] flex-col items-center justify-center rounded-xl bg-secondary py-10">
          <h1 className="mb-8 text-center">
            Log in to the <br /> Expense Tracker
          </h1>
          <Button
            className="flex items-center gap-4 rounded-xl bg-[#4285F4] px-6 py-2 font-semibold text-white"
            onClick={() => signIn("google")}
            icon={<AiFillGoogleCircle size={"1.5em"} />}
          >
            Continue with Google
          </Button>{" "}
          <Button
            className="mt-4 flex items-center gap-4 rounded-xl bg-[#404EED] px-6 py-2 font-semibold text-white hover:bg-[#4752C4]"
            onClick={() => signIn("discord")}
            icon={<BsDiscord size={"1.5em"} />}
          >
            Continue with Discord
          </Button>{" "}
        </div>
      </div>
    </>
  );
};

export default SignIn;
