import { type NextPage } from "next";
import { signIn, useSession } from "next-auth/react";
import { type FormEventHandler, useEffect, useState } from "react";
import Login from "../components/Login/Login";
import Link from "next/link";
import Button from "../components/shared/buttons/Button";
import { BsDiscord } from "react-icons/bs";
import Router, { useRouter } from "next/router";
import Head from "next/head";
import { useGetPageTitle } from "../hooks/useGetPageTitle";
import Loader from "../components/shared/Loader";

const SignIn: NextPage = () => {
  const { status } = useSession();
  const router = useRouter();
  const { title } = useGetPageTitle(router.pathname);

  const [userInfo, setUserInfo] = useState({ email: "", password: "" });

  useEffect(() => {
    if (status === "authenticated") Router.replace("/");
  }, [status]);

  const handleSubmit: FormEventHandler<HTMLFormElement> = async (e) => {
    // validate your userinfo
    e.preventDefault();

    const res = await signIn("credentials", {
      email: userInfo.email,
      password: userInfo.password,
      redirect: false,
    });

    console.log(res);
  };

  if (status === "loading")
    return (
      <div className="flex h-screen w-full justify-center bg-main">
        <Loader />
      </div>
    );
  if (status === "authenticated") return null;

  return (
    <>
      <Head>
        <title>Expense Tracker | {title}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/public/favicon.ico" />
      </Head>
      <div className="flex">
        <div className="h-screen w-1/2 bg-teal-200">LEFT SIDE</div>
        <div className="flex w-1/2 flex-col items-center justify-center">
          <Login />
          <Link href="/forgot-password" className="w-full">
            <p className="mt-2 px-28 text-right text-sm opacity-60">
              Forgot password?
            </p>
          </Link>
          <Button
            className="mt-16 flex items-center gap-4 rounded-xl bg-[#404EED] px-6 py-2 font-semibold text-white hover:bg-[#4752C4]"
            onClick={() => signIn("discord")}
            icon={<BsDiscord size={"1.5em"} />}
          >
            Sign In with Discord
          </Button>{" "}
        </div>
      </div>
    </>
  );
};

export default SignIn;
